name: Deploy

on:
  push:
  release:
    types: [published]

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
      - name: Authenticate to Google Cloud
        run: |
          echo ${{ secrets.GOOGLE_CLOUD_KEY }} | base64 --decode > "$HOME"/google-cloud-key.json
          gcloud auth activate-service-account --key-file="$HOME"/google-cloud-key.json
      - name: Deploy to Cloud Run
        run: bin/deploy.sh
